<a href="https://colab.research.google.com/github/BrenoSilvaProgramador/Pyhton_Aprendizado/blob/main/Introdu%C3%A7%C3%A3o_ao%20_Python-principais_Comandos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Utilizando if e else em Python


In [ ]:
# Utilizando if e else em Python

#____________________________________________________________#
                      #programa 01
#____________________________________________________________#

subtracao = 5 - 3

if subtracao == 2:
    print(subtracao == 2, '\n')
else :
    print('false\n')

#____________________________________________________________#
                      #programa 02
#____________________________________________________________#

idade = int(input('Qual a sua idade?')) #tratamento de dados!

if idade > 5 and idade < 18:
  print('Você tem menos de 18 anos!')
elif idade < 5:
  print('Insira uma idade valida seu palhaço!')
elif idade >= 18 and idade < 50:
  print('Você é um adulto!')
else:
  print('Você é um velho!')


#Utilizando for no Python

In [ ]:
# Utilizando for em Python

#____________________________________________________________#
                      #programa 01
#____________________________________________________________#

for n in range(2):
  print('\n', n, '--> Eu sou um...')

#____________________________________________________________#
                      #programa 02
#____________________________________________________________#

palavra = 'Programação'

for i in palavra:
  print('\n', i)

#____________________________________________________________#
                      #programa 03
#____________________________________________________________#

lista = [1, 2, 3, 45, 78]
for contador in lista:
  print('\n',contador, lista)

#Utilizando a função Input e tratando dados em Python


In [ ]:
1
#Funcao input e tratamento de dados
Nome = input('Qual o seu nome?')
print(Nome, 'Bem Vindo !')

numero_01 = int(input('Favor insira um numero: ')) #tratamento de dados String -> Int
numero_02 = int(input('Favor insira um numero: ')) #tratamento de dados String -> Int
soma = numero_01 + numero_02
print('A somatoria do numero', numero_01, 'com o', numero_02, 'e:', soma)

#Usando o While em Python


In [ ]:
# While em Python

#____________________________________________________________#
                      #programa 01
#____________________________________________________________#
import time #biblioteca time
contador = 0
while contador < 5:
  print('ainda nao deu!')
  contador += 1
  time.sleep(1) #funcao da biblioteca time
  if contador == 3:
    break   # comando break
print('Agora deu!')

#____________________________________________________________#
                      #programa 02
#____________________________________________________________#

numero = int(input('Digite um numero: '))
fatorial = numero
contador = 1 
while (numero-contador) > 1:
  fatorial *= (numero-contador)
  contador += 1
print("{0}! = {1}".format(numero,fatorial))

#Bibliotecas em Python

In [ ]:
#Bibliotecas em Python

#biblioteca math
import math 
print(math.factorial(5))

#biblioteca datetime
import datetime 
datetime.date.isoformat(datetime.date.today())


#Criando Funções em Python

In [ ]:
def soma():
  numero_01 = float(input('Insira um numero:'))
  numero_02 = float(input('Insira outro numero:'))
  soma = numero_01 + numero_02
  if soma > 100:
    print('A soma dos numeros:', numero_01, 'e', numero_02, 'resulta em:', soma,'\nUm numero que e maior que 100!')
  else:
    print('A soma dos numeros:', numero_01, 'e', numero_02, 'resulta em:', soma)

soma()

#Listas em Python

In [ ]:
#Listas em Python ---> [] <---

#____________________________________________________________#

                      #programa 01
#____________________________________________________________#
lista_01 = [1,2,3]
print(type(lista_01))

lista_02 = [ [1,2,3],  [4,5,6],  [7,8,9] ]
print(type(lista_02))

print(lista_01[0])    #posicao 01
print(lista_01[1])    #posicao 02
print(lista_02[2])    #posicao 03
print(lista_02[2][0]) #posicao da lista 2 na posicao 0

select = lista_02[1]
print(select)
print(type(select))



#____________________________________________________________#

                      #programa 02
#____________________________________________________________#

import random
cidades = ['Sao Paulo', 'Rio de Janeiro', 'Belo Horizonte',' Vitoria']
escolhida = random.choice(cidades) #escolhe um elemento alatorio da lista cidades
print('\nA cidade escolhida foi: ', escolhida)

a = [1, 2, 3]
a.append(15)  #adiciona um elemento no final da lista
print('\n',a)
b = [4,5,6]
for item in b:
  a.append(item)
print('\n', a)

#____________________________________________________________#

                      #exercicio 01
#____________________________________________________________#

x= [2,4,10,6]
nova = []
for i in x:
  nova.append(float(i))
print('\n\n', nova)

#Tupla em Python

In [ ]:
#Tupla em Python ---> Tuplas são lista que não podem ser alteradas (comandos como o dell não funcionam!) ---> () <---

Tupla = (1, 2, 4, 9)
print(Tupla)

lista = [1, 2, 4, 8, 16]
Tupla = tuple(lista)
print(Tupla)
print(type(Tupla))


(1, 2, 4, 9)
(1, 2, 4, 8, 16)
<class 'tuple'>


#Dicionario em Python

In [ ]:
#Dicionario ---> {} <---

Dicionario = {'Curso'            : 'Arduino', 
              'Aluno'            : 'Breno Silva',
              'Plataforma'       : 'CFBcursos',
              'Preço'            : 'Gratuito',
              'Lindeza do aluno' : 10}

print('Aluno: ', Dicionario['Aluno'])
print('Nota de Beleza: ', Dicionario['Lindeza do aluno'])
Dicionario = {'pre-requsito' :  'Programação em C'}
print(Dicionario.keys())
print(Dicionario.values())
print(Dicionario.items())
#Dicionario.clear() Comando para limpar o dicionario

Aluno:  Breno Silva
Nota de Beleza:  10
dict_keys(['pre-requsito'])
dict_values(['Programação em C'])
dict_items([('pre-requsito', 'Programação em C')])


#Manipulando Strings

In [ ]:
#Manipulando Strings

frase = 'eu estou amando programar em Python :('
print(frase)
print(frase[0:15])
print(frase[0:15:2])
print(frase.count('u'))
print(len(frase))
print(frase.replace('amando','odiando'))

#Funcao Lambda e Funções anonimas

In [ ]:
#Funcao básica em Python ----------------------

def soma_quadrados(a,b):
  soma = a**2 + b**2
  return soma

a = float(input('Insira o primeiro valor: '))
b = float(input('Insira o segundo valor: '))

print('os valores :', soma_quadrados(a,b))

#Função Lambda --------------------------------

soma_quadradosL = lambda a, b: a**2 + b**2

a = float(input('Insira o primeiro valor: '))
b = float(input('Insira o segundo valor: '))

print('os valores', soma_quadradosL(a,b))

f = lambda x : x / 2
x = float(input('Insira um valor e descubra sua metade: '))
print('O valor: ', f(x))

#Funcao map()
kph = [30, 20, 10, 50, 60, 75, 90]
mph = []

for contador in kph:
  mph.append(float(contador/1.61))
print(mph)

mph2 = list(map(lambda x: x/1.61, kph))
print(mph2);

# List Comprehension
mph3 = [x/1.61 for x in kph]
print(mph3)


Insira o primeiro valor: 10
Insira o segundo valor: 20
os valores : 500.0
Insira o primeiro valor: 34
Insira o segundo valor: 12
os valores 1300.0
Insira um valor e descubra sua metade: 12
O valor:  6.0
[18.633540372670808, 12.422360248447204, 6.211180124223602, 31.05590062111801, 37.267080745341616, 46.58385093167701, 55.90062111801242]
[18.633540372670808, 12.422360248447204, 6.211180124223602, 31.05590062111801, 37.267080745341616, 46.58385093167701, 55.90062111801242]
[18.633540372670808, 12.422360248447204, 6.211180124223602, 31.05590062111801, 37.267080745341616, 46.58385093167701, 55.90062111801242]


#Numpy em Python

In [ ]:
#matrizes e vetores em Python
import numpy as np
a = np.array([1,2,3])
print(a)
b = np.array([ (1,2,3), 
               (4,5,6), 
               (7,8,9),
              (10,11,12) ])
print('\n', b)
c= np.ones((4,3))
print('\n', c)

d = np.eye(4)
print('\n', d)

#Operações especiais 
# .min ---> retorna o menor valor  
# .max ---> retorna o maior valor
# .sun ---> retorna a somatoria dos valores
# .mean ---> retorna a media dos valores
# .std ---> retorna o desvio padrao

[1 2 3]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


12

#Biblioteca Pandas no Python